### ISSUE TITLE
on macOS \L in sed expression doesn't work

### ISSUE THREAD

**Issue by ajanian** [voronkovich/gitignore.plugin.zsh#8]
The version of sed that ships with macOS doesn't work well with the \L expression.  All the available choices in the template list are prepended with L.  This is a gnu sed extension.  I think the solution is to have an environment variable that points to the sed location.  I'm happy to provide a PR if you would like.  In my case I did brew install gnu-sed and then I use that version of sed which is gsed

**Comment by ajanian** [comment]
As a short term fix you can edit the zsh script gitignore.plugin.zsh to remove the \L from the sed expression on line 54 OR you can install gsed and leave the \L and change the sed command to be gsed

**Comment by voronkovich** [comment]
@ajanian, Thank you for investigation of this problem! I would appreciate the PR. I think we could try to use `tr` utility to lowercase templates names.

**Comment by ajanian** [comment]
done.  great idea on tr.  PR submitted
